### ISSUE TITLE
User Scenarios Revision

### ISSUE THREAD

**Issue by oncelkeles** [bounswe/bounswe2020group8#91]
**Documentation description:**
User scenarios should be updated according to the changes in the requirements.

**Deadline**: 08.11.2020

**Document source**:
[User Scenarios](https://github.com/bounswe/bounswe2020group8/wiki/User-Scenarios-&-Mockups)

**Comment by oncelkeles** [comment]
The revision is done. The changes can be seen here: [link](https://github.com/bounswe/bounswe2020group8/wiki/User-Scenarios-&-Mockups/_compare/2141c968bf119e76e9cb6bd247678bd6a2f9e88c...dd7974c319d67e0a4647ab8377acb8b677275278)

**Comment by oztasoi** [comment]
@oncelkeles The reorganization of user scenarios for the current state of requirements are quite fine 🚀  but we need at least one more scenario that relates to our project plan and it must be done before general testing procedure since it is planned to be illustrated for our incoming customer milestone. 🛃
